# Numpy Introduction and usage

## One Dimensional Array

In [4]:
import numpy as np

In [54]:
array1=np.array([10,20,30,40,50,80])

In [55]:
print(array1)

[10 20 30 40 50 80]


## Two Dimensional Array

In [8]:
array2=np.array([[10,20,30],[40,50,60]])

In [9]:
print(array2)

[[10 20 30]
 [40 50 60]]


## Three Dimensional Array

In [10]:
array3=np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,70]]])

In [11]:
print(array3)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 70]]]


## Findout Dimension of NumPy array

In [12]:
print('First Array Dimension:\t',array1.ndim)

First Array Dimension:	 1


In [13]:
print('Second Array Dimension:\t',array2.ndim)

Second Array Dimension:	 2


In [14]:
print('Third Array Dimension:\t',array3.ndim)

Third Array Dimension:	 3


# Task 1: Write an array of 5 students marks using NumPy
        ## Marks are: 80,70,75,99,89

In [21]:
marks_array=np.array([80,70,75,99,89])

In [23]:
print('Array of Marks:\t',marks_array)

Array of Marks:	 [80 70 75 99 89]


# Write an array: to take Marks of 5 students in 3 subjects using NumPy
## Math, English, Chemistry
### [[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]

In [25]:
array_marks_subjects=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print("2D Array Example:\n",array_marks_subjects)

2D Array Example:
 [[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


# Write an array: to take Marks of 4 students in 3 Subjects for two semester using NumPy
    ## Students Name are: 'Amit','Sha','Xi','Arif'
    ## Subjects: Math, English, Chemistry
    ## Semester: Sem1, Sem2
    ## 4*3*2
    ## [[[85,88],[78,82],[90,95]],[[76,70],[40,45],[90,90]],[[80,86],[78,82],[90,95]],[[85,88],[78,82],[70,90]]]

In [29]:
marks_subject_sem=np.array([[[85,88],[78,82],[90,95]],[[76,70],[40,45],[90,90]],[[80,86],[78,82],[90,95]],[[85,88],[78,82],[70,90]]])
print(marks_subject_sem)

[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 90]]

 [[80 86]
  [78 82]
  [90 95]]

 [[85 88]
  [78 82]
  [70 90]]]


# Write an array: to take weather of 2 cities in 3 days for three times in a day; Morning, Noon, Evening
    ## Cities name: Kuala Lumpur, Delhi
    ## Saturday, Sunday, Monday
    ## 3 time slots: Morning, Noon, Evening

## Create one 3D Array for this using Numpy and print it

In [40]:
weather_data=np.array([
    [#KL
        [25,27,30],
        [26,25,27],
        [25,26,27]
    ],
    [#Delhi
        [27,25,29],
        [23,22,24],
        [24,25,26]
    ]
])
    
print("Weather Data of Kuala Lumpur and Delhi ('C):\n",weather_data)

Weather Data of Kuala Lumpur and Delhi ('C):
 [[[25 27 30]
  [26 25 27]
  [25 26 27]]

 [[27 25 29]
  [23 22 24]
  [24 25 26]]]


## Basic Information

In [56]:
print(array1)

[10 20 30 40 50 80]


In [57]:
print("Shape of array1:\t",array1.shape)

Shape of array1:	 (6,)


In [58]:
print("Size of array1:\t",array1.size)

Size of array1:	 6


In [59]:
print("Dimension of array1:\t",array1.ndim)

Dimension of array1:	 1


In [60]:
print("Data Type of array1:\t",array1.dtype)

Data Type of array1:	 int64


In [66]:
students=np.array(['Ali Dhia','Sha','Xi','Meena','Kumar'])

In [67]:
print(students)

['Ali Dhia' 'Sha' 'Xi' 'Meena' 'Kumar']


In [68]:
print("Shape of students:\t",students.shape)
print("Size of students:\t",students.size)
print("Dimension of students:\t",students.ndim)
print("Data Type of students:\t",students.dtype)

Shape of students:	 (5,)
Size of students:	 5
Dimension of students:	 1
Data Type of students:	 <U8


# Mathematical Operation

## 1

In [69]:
print(array1)

[10 20 30 40 50 80]


In [72]:
total=np.sum(array1)

In [73]:
print(total)

230


In [79]:
print("Mean\t\t:",np.mean(array1))
print("Min\t\t:",np.min(array1))
print("Max\t\t:",np.max(array1))
print("Index of Min\t:",np.argmin(array1))
print("Index of Max\t:",np.argmax(array1))

Mean		: 38.333333333333336
Min		: 10
Max		: 80
Index of Min	: 0
Index of Max	: 5


## 2

In [80]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


#### #searching and sorting example in 1D Array

In [81]:
sorted_arr=np.sort(our_arr)
print("Sorted Array\t:",sorted_arr)

Sorted Array	: [ 100  200  300  300  400  500  600 1900 7000]


In [91]:
print("Is there any item greater than 500?\t:",np.any(sorted_arr>500))
print("All is greater than 500?\t\t:",np.all(sorted_arr>500))
print("All is greater than 99?\t\t\t:",np.all(sorted_arr>99))
print("Where is the values that is >500 (Index ie location)\t:",np.where(sorted_arr>500))
### or you can code this way:
print("All Number greater than 500 (Index ie location)\t\t:")
for num in np.where(sorted_arr>500):
    print(num)

Is there any item greater than 500?	: True
All is greater than 500?		: False
All is greater than 99?			: True
Where is the values that is >500 (Index ie location)	: (array([6, 7, 8]),)
All Number greater than 500 (Index ie location)		:
[6 7 8]


In [92]:
selected_values=sorted_arr[sorted_arr>500]
print(selected_values)

[ 600 1900 7000]


In [95]:
## or can code this way
for num in selected_values:
    print(num)

600
1900
7000


In [96]:
## or can code this way
for num in sorted_arr[sorted_arr>500]:
    print(num)

600
1900
7000


In [97]:
## or can code this way
for num in our_arr[our_arr>500]:
    print(num)

7000
1900
600


# Slicing 1D Array
    1. To take elements from starting index to end index
    2. e.g. [start:end]

In [98]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


In [99]:
slice_our_arr=our_arr[1:3]
print(slice_our_arr)

[200 300]


#### #printing from an Index to the last

In [100]:
print(our_arr[3:])

[7000  400  500  300 1900  600]


#### #printing the first Index number

In [101]:
print(our_arr[:4])

[ 100  200  300 7000]


In [102]:
print(our_arr[:7])

[ 100  200  300 7000  400  500  300]


# step
    ## [start:end:step]
    ## step: every step element

In [103]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[200 300 500]


In [105]:
every_third_element=sorted_arr[::3]
print(every_third_element)

[100 300 600]


In [106]:
every_third_element=sorted_arr[::3]
every_third_element

array([100, 300, 600])

In [109]:
print('Original Array')
print(sorted_arr)
print('Every THIRD Element Array')
every_third_element=sorted_arr[::3]
print(every_third_element)

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Every THIRD Element Array
[100 300 600]


## Slice Reverse

In [116]:
print('Original Array')
print(sorted_arr)
print('Reverse Array\t:',sorted_arr[::-1])

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Reverse Array	: [7000 1900  600  500  400  300  300  200  100]


In [119]:
print('Last Five Elements')
print(sorted_arr[-5:])
print('Slicing Done')

Last Five Elements
[ 400  500  600 1900 7000]
Slicing Done
