In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('students.xlsx')
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   39     45


In [7]:
marks=df['Marks'].to_numpy()
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [9]:
print('Highest Marks\t:',np.max(marks))
print('Lowest Marks\t:',np.min(marks))


Highest Marks	: 92
Lowest Marks	: 45


# .loc  : Label Based
# .iloc : Index Based

In [10]:
print('Original DataFrame')
print(df)
print('Location : Label Based')
print(df.loc[2])

Original DataFrame
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   39     45
Location : Label Based
Name     Bob
Age       21
Marks     78
Name: 2, dtype: object


In [15]:
## or you can try this
print('Original DataFrame')
print(df)
print('Location : Label Based')
print(df.loc[2,['Name','Marks']])

Original DataFrame
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   39     45
Location : Label Based
Name     Bob
Marks     78
Name: 2, dtype: object


In [13]:
print('Original DataFrame')
print(df)
print('Location : Index Based')
print(df.iloc[2,[1,2]])

Original DataFrame
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   39     45
Location : Index Based
Age      21
Marks    78
Name: 2, dtype: object


In [16]:
print('Original DataFrame')
print(df)
print('Location : Index Based')
print(df.iloc[4])

Original DataFrame
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   39     45
Location : Index Based
Name     Sam
Age       25
Marks     90
Name: 4, dtype: object


# Axis in NumPy:
    1. Axis 0: Vertical direction: works column-wise
    2. Axis 1: Horizontal direction: works row-wise
# We have two students marks in 3 subjects
    # [[45,40,49],[30,45,49]]

In [17]:
marks_arr=np.array([[45,40,49],[30,45,49]])
print(marks_arr)

[[45 40 49]
 [30 45 49]]


In [18]:
print('Sum down each column\t:',np.sum(marks_arr,axis=0))

Sum down each column	: [75 85 98]


In [19]:
print('Sum down each row\t:',np.sum(marks_arr,axis=1))

Sum down each row	: [134 124]


In [20]:
print('NumPy Array pf Marks\t:',marks)

NumPy Array pf Marks	: [85 90 78 92 90 45]


In [21]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   39     45


### Find the Student Name who got highest marks  [.idxmax()]

In [28]:
top_scorer=df.loc[df['Marks'].idxmax(),'Name']
print('Top Scorer\t:',top_scorer)

Top Scorer	: Sara


In [26]:
low_scorer=df.loc[df['Marks'].idxmin(),'Name']
print('Low Scorer\t:',low_scorer)

Low Scorer	: Rohit


In [30]:
top_index=df['Marks'].idxmax()
top_student=df.iloc[top_index,df.columns.get_loc('Name')]
print('Top student in the class is\t:',top_student)

Top student in the class is	: Sara
